<?php

namespace Eutranet\Corporate\Database\Seeders;

use Illuminate\Database\Seeder;
use DB;
use Eutranet\Setup\Models\StaffMember;
use Exception;

class StaffSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     * @throws Exception
     */
    public function run()
    {
        $loginPrefix = 'login@';
        // From the original "Utilizadores" table
        $staffArray =
            [
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'acalcada',
                    'name' => 'André Calçada',
                    'agency_id' => '3',
                    'representante' => 'Areosa',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'acastro',
                    'name' => 'António Castro',
                    'agency_id' => '13',
                    'representante' => 'Famalicão',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'acosta',
                    'name' => 'Alvaro Costa',
                    'agency_id' => '3',
                    'representante' => 'Areosa',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'adelina',
                    'name' => 'Adelina Portimão',
                    'agency_id' => '25',
                    'representante' => 'Portimão',
                    'is_active' => '1',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'central',
                    'name' => 'Pv Central',
                    'agency_id' => '5',
                    'representante' => 'PV Central',
                    'is_active' => '1',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'aesteves',
                    'name' => 'Andreia Esteves',
                    'agency_id' => '3',
                    'representante' => 'Areosa',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'afaria',
                    'name' => 'Ana faria',
                    'agency_id' => '30',
                    'representante' => 'Torres Novas',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'afreire',
                    'name' => 'António Freire',
                    'agency_id' => '24',
                    'representante' => 'Paredes',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'aleal',
                    'name' => 'Ana Leal',
                    'agency_id' => '24',
                    'representante' => 'Paredes',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'amestre',
                    'name' => 'António Mestre',
                    'agency_id' => '9',
                    'representante' => 'EXAMADORA',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'amorais',
                    'name' => 'Ana Morais',
                    'agency_id' => '15',
                    'representante' => 'Vila Nova de Gaia',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'anaf',
                    'name' => 'Ana Faria',
                    'agency_id' => '23',
                    'representante' => 'Ourém',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'anunes',
                    'name' => 'Adelina Nunes',
                    'agency_id' => '5',
                    'representante' => 'PV Central',
                    'is_active' => '1',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'asantana',
                    'name' => 'Anabela Santana',
                    'agency_id' => '8',
                    'representante' => 'Elvas',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'asantos',
                    'name' => 'Ana Santos',
                    'agency_id' => '27',
                    'representante' => 'Setubal',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'asilva',
                    'name' => 'António Silva',
                    'agency_id' => '14',
                    'representante' => 'Faro',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'audit',
                    'name' => 'Audit',
                    'agency_id' => '5',
                    'representante' => 'PV Central',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'avieira',
                    'name' => 'Adriana Vieira',
                    'agency_id' => '24',
                    'representante' => 'Paredes',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'azevedo',
                    'name' => 'Alberto Azevedo',
                    'agency_id' => '24',
                    'representante' => 'Paredes',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'bcpetada',
                    'name' => 'Catarina Petada',
                    'agency_id' => '4',
                    'representante' => 'Braga',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'bguerreiro',
                    'name' => 'Bruno Guerreiro',
                    'agency_id' => '14',
                    'representante' => 'Faro',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'bjcosta',
                    'name' => 'Joana Costa',
                    'agency_id' => '4',
                    'representante' => 'Braga',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'carlap',
                    'name' => 'Carla Pinto',
                    'agency_id' => '12',
                    'representante' => 'Expo-Sul',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'carlosv',
                    'name' => 'Carlos Varela',
                    'agency_id' => '27',
                    'representante' => 'Setubal',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'ccient',
                    'name' => 'Conselho Cientifíco',
                    'agency_id' => '5',
                    'representante' => 'PV Central',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'ccorreia',
                    'name' => 'Claúdia Sofia Correia',
                    'agency_id' => '26',
                    'representante' => 'Porto',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'ccunha',
                    'name' => 'Carla Cunha',
                    'agency_id' => '5',
                    'representante' => 'PV Central',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'cmacedo',
                    'name' => 'carla macedo',
                    'agency_id' => '12',
                    'representante' => 'Expo-Sul',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'cpetada',
                    'name' => 'Catarina Petada',
                    'agency_id' => '3',
                    'representante' => 'Areosa',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'cpinto',
                    'name' => 'Conceição Pinto',
                    'agency_id' => '5',
                    'representante' => 'PV Central',
                    'is_active' => '1',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'crosa',
                    'name' => 'Carla Rosa',
                    'agency_id' => '9',
                    'representante' => 'EXAMADORA',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'cvarela',
                    'name' => 'Carlos Varela',
                    'agency_id' => '21',
                    'representante' => 'Odivelas',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'doliveira',
                    'name' => 'Daniela Oliveira',
                    'agency_id' => '28',
                    'representante' => 'Sintra',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'dsimoes',
                    'name' => 'Deus Simoes',
                    'agency_id' => '28',
                    'representante' => 'Sintra',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'ecarlos',
                    'name' => 'Elzita Carlos',
                    'agency_id' => '1',
                    'representante' => 'Almada',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'eccunha',
                    'name' => 'Carla Cunha',
                    'agency_id' => '12',
                    'representante' => 'Expo-Sul',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'elcarlos',
                    'name' => 'Elzita Carlos',
                    'agency_id' => '28',
                    'representante' => 'Sintra',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'eoliveira',
                    'name' => 'Estefania Oliveira',
                    'agency_id' => '13',
                    'representante' => 'Famalicão',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'fccunha',
                    'name' => 'Carla Cunha',
                    'agency_id' => '13',
                    'representante' => 'Famalicão',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'fcosta',
                    'name' => 'Fernando Costa',
                    'agency_id' => '1',
                    'representante' => 'Almada',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'ffelix',
                    'name' => 'Fátima Félix',
                    'agency_id' => '18',
                    'representante' => 'Maia',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'florbelaPVC',
                    'name' => 'Florbela PVCoimbra',
                    'agency_id' => '6',
                    'representante' => 'Coimbra',
                    'is_active' => '1',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'FlorbelaPVP',
                    'name' => 'Florbela PVPorto',
                    'agency_id' => '26',
                    'representante' => 'Porto',
                    'is_active' => '1',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'fmota',
                    'name' => 'Marina de Fátima Moreira Mota',
                    'agency_id' => '24',
                    'representante' => 'Paredes',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'foliveira',
                    'name' => 'Florbela Oliveira',
                    'agency_id' => '5',
                    'representante' => 'PV Central',
                    'is_active' => '1',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'fsarrato',
                    'name' => 'Filipa Sarrato',
                    'agency_id' => '8',
                    'representante' => 'Elvas',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'fsilva',
                    'name' => 'Fulvia Silva',
                    'agency_id' => '24',
                    'representante' => 'Paredes',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'gestorva0',
                    'name' => 'gestorva0',
                    'agency_id' => '5',
                    'representante' => 'PV Central',
                    'is_active' => '1',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'gestorva1',
                    'name' => 'gestorva1',
                    'agency_id' => '5',
                    'representante' => 'PV Central',
                    'is_active' => '1',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'gestorva10',
                    'name' => 'Gestorva10',
                    'agency_id' => '5',
                    'representante' => 'PV Central',
                    'is_active' => '1',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'gestorva11',
                    'name' => 'gestorva11',
                    'agency_id' => '5',
                    'representante' => 'PV Central',
                    'is_active' => '1',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'gestorva12',
                    'name' => 'Gestorva12',
                    'agency_id' => '5',
                    'representante' => 'PV Central',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'gestorva13',
                    'name' => 'GestorVA13',
                    'agency_id' => '5',
                    'representante' => 'PV Central',
                    'is_active' => '1',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'Gestorva15',
                    'name' => 'Gestorva15',
                    'agency_id' => '5',
                    'representante' => 'PV Central',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'Gestorva16',
                    'name' => 'Gestorva16',
                    'agency_id' => '5',
                    'representante' => 'PV Central',
                    'is_active' => '1',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'Gestorva17',
                    'name' => 'Gestorva17',
                    'agency_id' => '5',
                    'representante' => 'PV Central',
                    'is_active' => '1',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'Gestorva18',
                    'name' => 'gestorva18',
                    'agency_id' => '5',
                    'representante' => 'PV Central',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'Gestorva19',
                    'name' => 'Gestorva19',
                    'agency_id' => '5',
                    'representante' => 'PV Central',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'gestorva2',
                    'name' => 'gestorva2',
                    'agency_id' => '5',
                    'representante' => 'PV Central',
                    'is_active' => '1',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'Gestorva20',
                    'name' => 'GestorVA20',
                    'agency_id' => '5',
                    'representante' => 'PV Central',
                    'is_active' => '1',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'gestorva3',
                    'name' => 'gestorva3',
                    'agency_id' => '5',
                    'representante' => 'PV Central',
                    'is_active' => '1',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'gestorva4',
                    'name' => 'gestorva4',
                    'agency_id' => '5',
                    'representante' => 'PV Central',
                    'is_active' => '1',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'gestorva5',
                    'name' => 'gestorva5',
                    'agency_id' => '5',
                    'representante' => 'PV Central',
                    'is_active' => '1',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'gestorva6',
                    'name' => 'gestorva6',
                    'agency_id' => '5',
                    'representante' => 'PV Central',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'gestorva7',
                    'name' => 'gestorva7',
                    'agency_id' => '5',
                    'representante' => 'PV Central',
                    'is_active' => '1',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'gestorva8',
                    'name' => 'gestorva8',
                    'agency_id' => '5',
                    'representante' => 'PV Central',
                    'is_active' => '1',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'gestorva9',
                    'name' => 'gestorva9',
                    'agency_id' => '5',
                    'representante' => 'PV Central',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'gmagalhaes',
                    'name' => 'Gonçalo Magalhães',
                    'agency_id' => '26',
                    'representante' => 'Porto',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'goncalves',
                    'name' => 'Leonardo Gonçalves',
                    'agency_id' => '28',
                    'representante' => 'Sintra',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'gsimoes',
                    'name' => 'Graça Simoes',
                    'agency_id' => '28',
                    'representante' => 'Sintra',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'haguiar',
                    'name' => 'Hugo Aguiar',
                    'agency_id' => '13',
                    'representante' => 'Famalicão',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'hmaia',
                    'name' => 'Hugo Maia',
                    'agency_id' => '5',
                    'representante' => 'PV Central',
                    'is_active' => '1',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'idantas',
                    'name' => 'Isabel Dantas',
                    'agency_id' => '26',
                    'representante' => 'Porto',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'imartins',
                    'name' => 'Inês Martins',
                    'agency_id' => '1',
                    'representante' => 'Almada',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'inmartins',
                    'name' => 'Inês Martins',
                    'agency_id' => '28',
                    'representante' => 'Sintra',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'isilva',
                    'name' => 'ISilva',
                    'agency_id' => '6',
                    'representante' => 'Coimbra',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'jcananao',
                    'name' => 'José Cananão',
                    'agency_id' => '12',
                    'representante' => 'Expo-Sul',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'jcastanheira',
                    'name' => 'Jorge Castanheira',
                    'agency_id' => '29',
                    'representante' => 'PvTeste',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'jcosta',
                    'name' => 'Joana Costa',
                    'agency_id' => '3',
                    'representante' => 'Areosa',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'jmaceda',
                    'name' => 'Joel Maceda',
                    'agency_id' => '5',
                    'representante' => 'PV Central',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'jpsoares',
                    'name' => 'João Soares',
                    'agency_id' => '6',
                    'representante' => 'Coimbra',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'jsilva',
                    'name' => 'Jorge Silva',
                    'agency_id' => '15',
                    'representante' => 'Vila Nova de Gaia',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'jsoares',
                    'name' => 'João Soares',
                    'agency_id' => '26',
                    'representante' => 'Porto',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'jteixeira',
                    'name' => 'José Teixeira',
                    'agency_id' => '1',
                    'representante' => 'Almada',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'lgoncalves',
                    'name' => 'Leonardo Gonçalves',
                    'agency_id' => '1',
                    'representante' => 'Almada',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'lmatos',
                    'name' => 'luisa.matos',
                    'agency_id' => '24',
                    'representante' => 'Paredes',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'lsantos',
                    'name' => 'Lurdes Santos',
                    'agency_id' => '5',
                    'representante' => 'PV Central',
                    'is_active' => '1',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'lugoncalves',
                    'name' => 'Luis Gonçalves',
                    'agency_id' => '1',
                    'representante' => 'Almada',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'mareias',
                    'name' => 'Miguel Areias',
                    'agency_id' => '15',
                    'representante' => 'Vila Nova de Gaia',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'marta',
                    'name' => 'Marta Castro',
                    'agency_id' => '20',
                    'representante' => 'Matosinhos',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'mcardoso',
                    'name' => 'Maria Cardoso',
                    'agency_id' => '21',
                    'representante' => 'Odivelas',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'mcastro',
                    'name' => 'Marta Castro',
                    'agency_id' => '6',
                    'representante' => 'Coimbra',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'mfernandes',
                    'name' => 'Marta Fernandes',
                    'agency_id' => '14',
                    'representante' => 'Faro',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'mjoao',
                    'name' => 'Maria João',
                    'agency_id' => '6',
                    'representante' => 'Coimbra',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'mmota',
                    'name' => 'margarida mota',
                    'agency_id' => '5',
                    'representante' => 'PV Central',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'msoares',
                    'name' => 'Marta Soares',
                    'agency_id' => '26',
                    'representante' => 'Porto',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'msolano',
                    'name' => 'Mário Solano',
                    'agency_id' => '9',
                    'representante' => 'EXAMADORA',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'mteixeira',
                    'name' => 'Miguel Teixeira',
                    'agency_id' => '15',
                    'representante' => 'Vila Nova de Gaia',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'nfonseca',
                    'name' => 'Nuno Fonseca',
                    'agency_id' => '21',
                    'representante' => 'Odivelas',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'npaulo',
                    'name' => 'Nuno Paulo',
                    'agency_id' => '16',
                    'representante' => 'Leiria',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'nsilva',
                    'name' => 'Nuno Silva',
                    'agency_id' => '14',
                    'representante' => 'Faro',
                    'is_active' => '0',
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'nunop',
                    'name' => 'Nuno Paulo',
                    'agency_id' => '7',
                    'representante' => 'Caldas da Rainha',
                    'is_active' => '0'
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'odivelas',
                    'name' => 'Odivelas',
                    'agency_id' => '21',
                    'representante' => 'Odivelas',
                    'is_active' => '0'
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'oficioso',
                    'name' => 'oficioso',
                    'agency_id' => '5',
                    'representante' => 'PV Central',
                    'is_active' => '1'
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'oliveira',
                    'name' => 'Florbela Oliveira',
                    'agency_id' => '12',
                    'representante' => 'Expo-Sul',
                    'is_active' => '0'
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'partners',
                    'name' => 'Partners',
                    'agency_id' => '5',
                    'representante' => 'PV Central',
                    'is_active' => '0'
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'pasilva',
                    'name' => 'Paulo Silva',
                    'agency_id' => '14',
                    'representante' => 'Faro',
                    'is_active' => '0'
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'paulap',
                    'name' => 'Paula Policiano',
                    'agency_id' => '18',
                    'representante' => 'Maia',
                    'is_active' => '1'
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'pedrosol',
                    'name' => 'Pedroso Leal',
                    'agency_id' => '23',
                    'representante' => 'Ourém',
                    'is_active' => '0'
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'pleal',
                    'name' => 'Pedroso Leal',
                    'agency_id' => '30',
                    'representante' => 'Torres Novas',
                    'is_active' => '0'
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'pmarques',
                    'name' => 'Paula Marques',
                    'agency_id' => '28',
                    'representante' => 'Sintra',
                    'is_active' => '0'
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'ppoliciano',
                    'name' => 'Paula Policiano',
                    'agency_id' => '5',
                    'representante' => 'PV Central',
                    'is_active' => '1'
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'pramos',
                    'name' => 'Paulo Ramos',
                    'agency_id' => '5',
                    'representante' => 'PV Central',
                    'is_active' => '0'
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'psilva',
                    'name' => 'paulo silva',
                    'agency_id' => '6',
                    'representante' => 'Coimbra',
                    'is_active' => '0'
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'razevedo',
                    'name' => 'Ricardo Azevedo',
                    'agency_id' => '13',
                    'representante' => 'Famalicão',
                    'is_active' => '0'
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'renaton',
                    'name' => 'Renato Noronha',
                    'agency_id' => '2',
                    'representante' => 'Amadora',
                    'is_active' => '0'
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'rjorge',
                    'name' => 'Rita Jorge',
                    'agency_id' => '12',
                    'representante' => 'Expo-Sul',
                    'is_active' => '0'
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'rlima',
                    'name' => 'Raul Lima',
                    'agency_id' => '30',
                    'representante' => 'Torres Novas',
                    'is_active' => '0'
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'rmarques',
                    'name' => 'Ricardo Marques',
                    'agency_id' => '15',
                    'representante' => 'Vila Nova de Gaia',
                    'is_active' => '0'
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'rmartins',
                    'name' => 'Ana Rita Martins',
                    'agency_id' => '5',
                    'representante' => 'PV Central',
                    'is_active' => '0'
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'rnoronha',
                    'name' => 'Renato Noronha',
                    'agency_id' => '17',
                    'representante' => 'Loures',
                    'is_active' => '0'
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'rsilva',
                    'name' => 'Ricardo Silva',
                    'agency_id' => '14',
                    'representante' => 'Faro',
                    'is_active' => '0'
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'sadelgado',
                    'name' => 'Sara Delgado',
                    'agency_id' => '28',
                    'representante' => 'Sintra',
                    'is_active' => '0'
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'safonseca',
                    'name' => 'Sandra Fonseca',
                    'agency_id' => '6',
                    'representante' => 'Coimbra',
                    'is_active' => '0'
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'sarac',
                    'name' => 'Sara Coelho',
                    'agency_id' => '24',
                    'representante' => 'Paredes',
                    'is_active' => '0'
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'scoelho',
                    'name' => 'Sara Coelho',
                    'agency_id' => '13',
                    'representante' => 'Famalicão',
                    'is_active' => '0'
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'sdantas',
                    'name' => 'Sandra Dantas',
                    'agency_id' => '26',
                    'representante' => 'Porto',
                    'is_active' => '0'
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'sdelgado',
                    'name' => 'Sara Delgado',
                    'agency_id' => '1',
                    'representante' => 'Almada',
                    'is_active' => '0'
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'sede',
                    'name' => 'Utilizador para introdução de Leads',
                    'agency_id' => '5',
                    'representante' => 'PV Central',
                    'is_active' => '0'
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'sferreira',
                    'name' => 'Sara Ferreira',
                    'agency_id' => '1',
                    'representante' => 'Almada',
                    'is_active' => '0'
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'sfonseca',
                    'name' => 'Sandra Fonseca',
                    'agency_id' => '26',
                    'representante' => 'Porto',
                    'is_active' => '0'
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'sheilas',
                    'name' => 'Sheila santos',
                    'agency_id' => '23',
                    'representante' => 'Ourém',
                    'is_active' => '0'
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'spereira',
                    'name' => 'Sónia Pereira',
                    'agency_id' => '1',
                    'representante' => 'Almada',
                    'is_active' => '0'
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'ssantos',
                    'name' => 'Sheila santos',
                    'agency_id' => '30',
                    'representante' => 'Torres Novas',
                    'is_active' => '0'
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'ssilva',
                    'name' => 'Sandra Dantas',
                    'agency_id' => '6',
                    'representante' => 'Coimbra',
                    'is_active' => '0'
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'tsoares',
                    'name' => 'Tiago Soares',
                    'agency_id' => '26',
                    'representante' => 'Porto',
                    'is_active' => '0'
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'uteste',
                    'name' => 'utilizadorteste',
                    'agency_id' => '29',
                    'representante' => 'PvTeste',
                    'is_active' => '0'
                ],
                [
                    'email' => random_int(1, 99999999) . '@florbelaoliveira.pt',
                    'login' => $loginPrefix . 'florbela',
                    'name' => 'Florbela Oliveira',
                    'agency_id' => '26',
                    'representante' => 'Porto',
                    'is_active' => '1',
                ],
            ];

        if (StaffMember::count() === 1) {
            $superStaff = StaffMember::where('id', 1);
            $superStaff->update([
                'agency_id' => 1
            ]);
            DB::table('staff_members')->insert(
                $staffArray
            );

            // After insertion, "representante" becomes an "agency_id" (foreign key)
            foreach (StaffMember::all() as $staffMember) {
                $agency = DB::table('agencies')->where('zone', '=', $staffMember->representante)->get()->first() ?: null;
                StaffMember::find($staffMember->id)->update(['agency_id' => $agency?->id ?: '1']);
            }

            StaffMember::find(139)->update(['is_super' => true]);
            // We now have StaffMember BelongsTo Agency
        }
    }
}
